server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.djun.demo.model                 # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: deptservice-provider-8001

  datasource:
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型

    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
    tomcat:
      max-wait: 30000
      # 配置间隔多久才进行一次检测需要关闭的空闲连接，单位是毫秒

  redis:
    host: 10.12.9.108
    # Redis数据库索引（默认为0）
    database: 0
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 3000ms

  rabbitmq:
    host: 10.12.9.108
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

  data:
    mongodb:
      host: 10.12.9.108
      port: 27017
      database: cloud01

eureka:
  client:
    #客户端注册进eureka服务列表内
    service-url:
      # 1、单机版配置
       defaultZone: http://localhost:7001/eureka/
      # 2、集群版配置
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 服务名称修改
    instance-id: deptservice-8001.com
    # 设置访问信息有IP 信息提示
    prefer-ip-address: true

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间


# 加密密钥
password:
  key: "djun"



# info是当前微服务的信息
info:
  app.name: deptservice-8001
  company.name: com.djun.demo
  build.artifactId: $project.artifactId$
  build.version: $project.version$

# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.djun.demo.mapper: debug
    com.djun.demo.service: debug

